[project]
name = "novapasta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Luis", email = "tecnicoroot@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
novapasta = "novapasta:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
